<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MenuBarSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * 
     * Este seeder carga el menú completo del bar con tragos, comidas y bebidas
     * NOTA: Los precios NO incluyen IVA
     */
    public function run(): void
    {
        // Limpiar datos existentes
        DB::table('categoria_producto')->delete();
        DB::table('productos')->delete();
        
        // Resetear IDs
        DB::statement('ALTER SEQUENCE productos_id_seq RESTART WITH 1');
        
        $productos = [
            // ========== TRAGOS CLÁSICOS ==========
            [
                'codigo' => 'TRG001',
                'nombre' => 'Caipirinha',
                'tipo_producto' => 'trago',
                'aplica_descuento_trago' => true,
                'stock' => 999,
                'precio_venta' => 15000,
                'descripcion' => 'Limón, jugo de limón, Velho Bareiro y azúcar',
                'impuesto' => 0, // Sin IVA
                'fecha_vencimiento' => null,
                'img_path' => null,
                'estado' => 1,
                'marca_id' => 7, // Casa Propia
                'presentacione_id' => 8, // Copa
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'codigo' => 'TRG002',
                'nombre' => 'Caipiroska',
                'tipo_producto' => 'trago',
                'aplica_descuento_trago' => true,
                'stock' => 999,
                'precio_venta' => 15000,
                'descripcion' => 'Limón, jugo de limón, vodka y azúcar',
                'impuesto' => 0,
                'fecha_vencimiento' => null,
                'img_path' => null,
                'estado' => 1,
                'marca_id' => 7,
                'presentacione_id' => 8,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'codigo' => 'TRG003',
                'nombre' => 'Caipiruva',
                'tipo_producto' => 'trago',
                'aplica_descuento_trago' => true,
                'stock' => 999,
                'precio_venta' => 15000,
                'descripcion' => 'Limón, jugo de limón, vino tinto, Velho Bareiro y azúcar',
                'impuesto' => 0,
                'fecha_vencimiento' => null,
                'img_path' => null,
                'estado' => 1,
                'marca_id' => 7,
                'presentacione_id' => 8,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'codigo' => 'TRG004',
                'nombre' => 'Mojito',
                'tipo_producto' => 'trago',
                'aplica_descuento_trago' => true,
                'stock' => 999,
                'precio_venta' => 15000,
                'descripcion' => 'Limón, jugo de limón, ron blanco, menta fresca, soda y azúcar',
                'impuesto' => 0,
                'fecha_vencimiento' => null,
                'img_path' => null,
                'estado' => 1,
                'marca_id' => 7,
                'presentacione_id' => 8,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'codigo' => 'TRG005',
                'nombre' => 'Aperol',
                'tipo_producto' => 'trago',
                'aplica_descuento_trago' => true,
                'stock' => 999,
                'precio_venta' => 25000,
                'descripcion' => 'Aperol, espumante naranja, naranja, jugo de naranja',
                'impuesto' => 0,
                'fecha_vencimiento' => null,
                'img_path' => null,
                'estado' => 1,
                'marca_id' => 7,
                'presentacione_id' => 8,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'codigo' => 'TRG006',
                'nombre' => 'Piña Colada',
                'tipo_producto' => 'trago',
                'aplica_descuento_trago' => true,
                'stock' => 999,
                'precio_venta' => 20000,
                'descripcion' => 'Ron coco, piña y azúcar',
                'impuesto' => 0,
                'fecha_vencimiento' => null,
                'img_path' => null,
                'estado' => 1,
                'marca_id' => 7,
                'presentacione_id' => 8,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'codigo' => 'TRG007',
                'nombre' => 'Tequila Sunrise',
                'tipo_producto' => 'trago',
                'aplica_descuento_trago' => true,
                'stock' => 999,
                'precio_venta' => 20000,
                'descripcion' => 'Tequila, jugo de naranja, granadina',
                'impuesto' => 0,
                'fecha_vencimiento' => null,
                'img_path' => null,
                'estado' => 1,
                'marca_id' => 7,
                'presentacione_id' => 8,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'codigo' => 'TRG008',
                'nombre' => 'Cuba Libre',
                'tipo_producto' => 'trago',
                'aplica_descuento_trago' => true,
                'stock' => 999,
                'precio_venta' => 15000,
                'descripcion' => 'Ron blanco, limón, jugo de limón y Coca Cola',
                'impuesto' => 0,
                'fecha_vencimiento' => null,
                'img_path' => null,
                'estado' => 1,
                'marca_id' => 7,
                'presentacione_id' => 8,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'codigo' => 'TRG009',
                'nombre' => 'Destornillador',
                'tipo_producto' => 'trago',
                'aplica_descuento_trago' => true,
                'stock' => 999,
                'precio_venta' => 15000,
                'descripcion' => 'Jugo de naranja y vodka',
                'impuesto' => 0,
                'fecha_vencimiento' => null,
                'img_path' => null,
                'estado' => 1,
                'marca_id' => 7,
                'presentacione_id' => 8,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'codigo' => 'TRG010',
                'nombre' => 'Russo Negro',
                'tipo_producto' => 'trago',
                'aplica_descuento_trago' => true,
                'stock' => 999,
                'precio_venta' => 20000,
                'descripcion' => 'Licor de café y vodka',
                'impuesto' => 0,
                'fecha_vencimiento' => null,
                'img_path' => null,
                'estado' => 1,
                'marca_id' => 7,
                'presentacione_id' => 8,
                'created_at' => now(),
                'updated_at' => now()
            ],

            // ========== DAIQUIRIS ==========
            [
                'codigo' => 'DAI001',
                'nombre' => 'Daiquiri Frutilla',
                'tipo_producto' => 'trago',
                'aplica_descuento_trago' => true,
                'stock' => 999,
                'precio_venta' => 20000,
                'descripcion' => 'Ron blanco, zumo de limón, frutilla y azúcar',
                'impuesto' => 0,
                'fecha_vencimiento' => null,
                'img_path' => null,
                'estado' => 1,
                'marca_id' => 7,
                'presentacione_id' => 8,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'codigo' => 'DAI002',
                'nombre' => 'Daiquiri Durazno',
                'tipo_producto' => 'trago',
                'aplica_descuento_trago' => true,
                'stock' => 999,
                'precio_venta' => 20000,
                'descripcion' => 'Ron blanco, zumo de limón, durazno y azúcar',
                'impuesto' => 0,
                'fecha_vencimiento' => null,
                'img_path' => null,
                'estado' => 1,
                'marca_id' => 7,
                'presentacione_id' => 8,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'codigo' => 'DAI003',
                'nombre' => 'Daiquiri Piña',
                'tipo_producto' => 'trago',
                'aplica_descuento_trago' => true,
                'stock' => 999,
                'precio_venta' => 20000,
                'descripcion' => 'Ron blanco, zumo de limón, piña y azúcar',
                'impuesto' => 0,
                'fecha_vencimiento' => null,
                'img_path' => null,
                'estado' => 1,
                'marca_id' => 7,
                'presentacione_id' => 8,
                'created_at' => now(),
                'updated_at' => now()
            ],

            // ========== SANGRÍAS ==========
            [
                'codigo' => 'SAN001',
                'nombre' => 'Sangría Clásico',
                'tipo_producto' => 'trago',
                'aplica_descuento_trago' => true,
                'stock' => 999,
                'precio_venta' => 15000,
                'descripcion' => 'Vino tinto, jugo de naranja, azúcar',
                'impuesto' => 0,
                'fecha_vencimiento' => null,
                'img_path' => null,
                'estado' => 1,
                'marca_id' => 7,
                'presentacione_id' => 8,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'codigo' => 'SAN002',
                'nombre' => 'Sangría TuttiFrost',
                'tipo_producto' => 'trago',
                'aplica_descuento_trago' => true,
                'stock' => 999,
                'precio_venta' => 20000,
                'descripcion' => 'Vino tinto, jugo de naranja, frutilla y durazno, azúcar',
                'impuesto' => 0,
                'fecha_vencimiento' => null,
                'img_path' => null,
                'estado' => 1,
                'marca_id' => 7,
                'presentacione_id' => 8,
                'created_at' => now(),
                'updated_at' => now()
            ],

            // ========== OTROS TRAGOS ==========
            [
                'codigo' => 'OTR001',
                'nombre' => 'Fernet Cola',
                'tipo_producto' => 'trago',
                'aplica_descuento_trago' => true,
                'stock' => 999,
                'precio_venta' => 15000,
                'descripcion' => 'Raya de fernet, Coca Cola y hielo',
                'impuesto' => 0,
                'fecha_vencimiento' => null,
                'img_path' => null,
                'estado' => 1,
                'marca_id' => 7,
                'presentacione_id' => 8,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'codigo' => 'OTR002',
                'nombre' => 'Whiscola',
                'tipo_producto' => 'trago',
                'aplica_descuento_trago' => true,
                'stock' => 999,
                'precio_venta' => 15000,
                'descripcion' => 'Whisky, Coca Cola',
                'impuesto' => 0,
                'fecha_vencimiento' => null,
                'img_path' => null,
                'estado' => 1,
                'marca_id' => 7,
                'presentacione_id' => 8,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'codigo' => 'OTR003',
                'nombre' => 'Gin Tonic',
                'tipo_producto' => 'trago',
                'aplica_descuento_trago' => true,
                'stock' => 999,
                'precio_venta' => 20000,
                'descripcion' => 'Gin, agua tónica y rodaja de limón',
                'impuesto' => 0,
                'fecha_vencimiento' => null,
                'img_path' => null,
                'estado' => 1,
                'marca_id' => 7,
                'presentacione_id' => 8,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'codigo' => 'OTR004',
                'nombre' => 'Machu Picchu',
                'tipo_producto' => 'trago',
                'aplica_descuento_trago' => true,
                'stock' => 999,
                'precio_venta' => 25000,
                'descripcion' => 'Granadina, jugo de naranja, vodka, licor de menta',
                'impuesto' => 0,
                'fecha_vencimiento' => null,
                'img_path' => null,
                'estado' => 1,
                'marca_id' => 7,
                'presentacione_id' => 8,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'codigo' => 'OTR005',
                'nombre' => 'Green Frost',
                'tipo_producto' => 'trago',
                'aplica_descuento_trago' => true,
                'stock' => 999,
                'precio_venta' => 20000,
                'descripcion' => 'Blue Curaçao, jugo de naranja, Sprite y vodka',
                'impuesto' => 0,
                'fecha_vencimiento' => null,
                'img_path' => null,
                'estado' => 1,
                'marca_id' => 7,
                'presentacione_id' => 8,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'codigo' => 'OTR006',
                'nombre' => 'Electric',
                'tipo_producto' => 'trago',
                'aplica_descuento_trago' => true,
                'stock' => 999,
                'precio_venta' => 20000,
                'descripcion' => 'Vodka, jugo de limón, Blue Curaçao, Sprite y azúcar',
                'impuesto' => 0,
                'fecha_vencimiento' => null,
                'img_path' => null,
                'estado' => 1,
                'marca_id' => 7,
                'presentacione_id' => 8,
                'created_at' => now(),
                'updated_at' => now()
            ],

            // ========== SHOTS ==========
            [
                'codigo' => 'SHT001',
                'nombre' => 'Tequila',
                'tipo_producto' => 'trago',
                'aplica_descuento_trago' => false, // Los shots NO aplican descuento
                'stock' => 999,
                'precio_venta' => 10000,
                'descripcion' => 'Shot de tequila',
                'impuesto' => 0,
                'fecha_vencimiento' => null,
                'img_path' => null,
                'estado' => 1,
                'marca_id' => 6,
                'presentacione_id' => 7, // Shot
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'codigo' => 'SHT002',
                'nombre' => 'Jagger',
                'tipo_producto' => 'trago',
                'aplica_descuento_trago' => false,
                'stock' => 999,
                'precio_venta' => 15000,
                'descripcion' => 'Shot de Jägermeister',
                'impuesto' => 0,
                'fecha_vencimiento' => null,
                'img_path' => null,
                'estado' => 1,
                'marca_id' => 7,
                'presentacione_id' => 7,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'codigo' => 'SHT003',
                'nombre' => 'Bob Marley',
                'tipo_producto' => 'trago',
                'aplica_descuento_trago' => false,
                'stock' => 999,
                'precio_venta' => 15000,
                'descripcion' => 'Shot especial Bob Marley',
                'impuesto' => 0,
                'fecha_vencimiento' => null,
                'img_path' => null,
                'estado' => 1,
                'marca_id' => 7,
                'presentacione_id' => 7,
                'created_at' => now(),
                'updated_at' => now()
            ],

            // ========== PAPAS ==========
            [
                'codigo' => 'PAP001',
                'nombre' => 'Papas Tradicionales',
                'tipo_producto' => 'comida',
                'aplica_descuento_trago' => false,
                'stock' => 999,
                'precio_venta' => 12000,
                'descripcion' => 'Papas fritas tradicionales',
                'impuesto' => 0,
                'fecha_vencimiento' => null,
                'img_path' => null,
                'estado' => 1,
                'marca_id' => 7,
                'presentacione_id' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'codigo' => 'PAP002',
                'nombre' => 'Papas con Cheddar y Panceta',
                'tipo_producto' => 'comida',
                'aplica_descuento_trago' => false,
                'stock' => 999,
                'precio_venta' => 15000,
                'descripcion' => 'Papas fritas con cheddar y panceta',
                'impuesto' => 0,
                'fecha_vencimiento' => null,
                'img_path' => null,
                'estado' => 1,
                'marca_id' => 7,
                'presentacione_id' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'codigo' => 'PAP003',
                'nombre' => 'Salchipapa',
                'tipo_producto' => 'comida',
                'aplica_descuento_trago' => false,
                'stock' => 999,
                'precio_venta' => 20000,
                'descripcion' => 'Papas fritas con salchicha',
                'impuesto' => 0,
                'fecha_vencimiento' => null,
                'img_path' => null,
                'estado' => 1,
                'marca_id' => 7,
                'presentacione_id' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],

            // ========== PIZZAS ==========
            [
                'codigo' => 'PIZ001',
                'nombre' => 'Pizza Muzzarella',
                'tipo_producto' => 'comida',
                'aplica_descuento_trago' => false,
                'stock' => 999,
                'precio_venta' => 20000,
                'descripcion' => 'Salsa de tomate, muzzarella, katupiry, orégano (25×10 cm)',
                'impuesto' => 0,
                'fecha_vencimiento' => null,
                'img_path' => null,
                'estado' => 1,
                'marca_id' => 7,
                'presentacione_id' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'codigo' => 'PIZ002',
                'nombre' => 'Pizza Pepperoni',
                'tipo_producto' => 'comida',
                'aplica_descuento_trago' => false,
                'stock' => 999,
                'precio_venta' => 25000,
                'descripcion' => 'Salsa de tomate, muzzarella, pepperoni, katupiry, orégano (25×10 cm)',
                'impuesto' => 0,
                'fecha_vencimiento' => null,
                'img_path' => null,
                'estado' => 1,
                'marca_id' => 7,
                'presentacione_id' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'codigo' => 'PIZ003',
                'nombre' => 'Pizza Aceituna',
                'tipo_producto' => 'comida',
                'aplica_descuento_trago' => false,
                'stock' => 999,
                'precio_venta' => 20000,
                'descripcion' => 'Salsa de tomate, muzzarella, aceituna, katupiry, orégano (25×10 cm)',
                'impuesto' => 0,
                'fecha_vencimiento' => null,
                'img_path' => null,
                'estado' => 1,
                'marca_id' => 7,
                'presentacione_id' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'codigo' => 'PIZ004',
                'nombre' => 'Pizza Cheddar y Panceta',
                'tipo_producto' => 'comida',
                'aplica_descuento_trago' => false,
                'stock' => 999,
                'precio_venta' => 25000,
                'descripcion' => 'Salsa de tomate, muzzarella, cheddar, panceta, orégano (25×10 cm)',
                'impuesto' => 0,
                'fecha_vencimiento' => null,
                'img_path' => null,
                'estado' => 1,
                'marca_id' => 7,
                'presentacione_id' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'codigo' => 'PIZ005',
                'nombre' => 'Pizza Doggies',
                'tipo_producto' => 'comida',
                'aplica_descuento_trago' => false,
                'stock' => 999,
                'precio_venta' => 28000,
                'descripcion' => 'Salsa de tomate, salchicha, muzzarella, katupiry, mostaza, orégano (25×10 cm)',
                'impuesto' => 0,
                'fecha_vencimiento' => null,
                'img_path' => null,
                'estado' => 1,
                'marca_id' => 7,
                'presentacione_id' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],

            // ========== HOT DOGS ==========
            [
                'codigo' => 'HOT001',
                'nombre' => 'Hot Dog Clásico',
                'tipo_producto' => 'comida',
                'aplica_descuento_trago' => false,
                'stock' => 999,
                'precio_venta' => 12000,
                'descripcion' => 'Pan, salchicha grill, mostaza, mayonesa, ketchup',
                'impuesto' => 0,
                'fecha_vencimiento' => null,
                'img_path' => null,
                'estado' => 1,
                'marca_id' => 7,
                'presentacione_id' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'codigo' => 'HOT002',
                'nombre' => 'Hot Dog Cheddar y Bacon',
                'tipo_producto' => 'comida',
                'aplica_descuento_trago' => false,
                'stock' => 999,
                'precio_venta' => 15000,
                'descripcion' => 'Pan, salchicha grill, cheddar y bacon',
                'impuesto' => 0,
                'fecha_vencimiento' => null,
                'img_path' => null,
                'estado' => 1,
                'marca_id' => 7,
                'presentacione_id' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'codigo' => 'HOT003',
                'nombre' => 'Hot Dog Pizza Pepperoni',
                'tipo_producto' => 'comida',
                'aplica_descuento_trago' => false,
                'stock' => 999,
                'precio_venta' => 20000,
                'descripcion' => 'Pan, salchicha grill, muzzarella, katupiry, orégano, pepperoni',
                'impuesto' => 0,
                'fecha_vencimiento' => null,
                'img_path' => null,
                'estado' => 1,
                'marca_id' => 7,
                'presentacione_id' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'codigo' => 'HOT004',
                'nombre' => 'Hot Dog Pizza Aceituna',
                'tipo_producto' => 'comida',
                'aplica_descuento_trago' => false,
                'stock' => 999,
                'precio_venta' => 18000,
                'descripcion' => 'Pan, salchicha grill, muzzarella, katupiry, orégano, aceituna',
                'impuesto' => 0,
                'fecha_vencimiento' => null,
                'img_path' => null,
                'estado' => 1,
                'marca_id' => 7,
                'presentacione_id' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],

            // ========== COMBOS ==========
            [
                'codigo' => 'CMB001',
                'nombre' => 'Combo Clásico',
                'tipo_producto' => 'comida',
                'aplica_descuento_trago' => false,
                'stock' => 999,
                'precio_venta' => 17000,
                'descripcion' => 'Hot dog clásico + papas fritas',
                'impuesto' => 0,
                'fecha_vencimiento' => null,
                'img_path' => null,
                'estado' => 1,
                'marca_id' => 7,
                'presentacione_id' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'codigo' => 'CMB002',
                'nombre' => 'Combo Cheddar y Bacon',
                'tipo_producto' => 'comida',
                'aplica_descuento_trago' => false,
                'stock' => 999,
                'precio_venta' => 20000,
                'descripcion' => 'Hot dog cheddar y bacon + papas fritas',
                'impuesto' => 0,
                'fecha_vencimiento' => null,
                'img_path' => null,
                'estado' => 1,
                'marca_id' => 7,
                'presentacione_id' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'codigo' => 'CMB003',
                'nombre' => 'Combo Pizzadog',
                'tipo_producto' => 'comida',
                'aplica_descuento_trago' => false,
                'stock' => 999,
                'precio_venta' => 25000,
                'descripcion' => 'Hot dog pizza + papas fritas',
                'impuesto' => 0,
                'fecha_vencimiento' => null,
                'img_path' => null,
                'estado' => 1,
                'marca_id' => 7,
                'presentacione_id' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],

            // ========== AGUAS Y GASEOSAS ==========
            [
                'codigo' => 'BEB001',
                'nombre' => 'Coca Cola 1 L',
                'tipo_producto' => 'bebida',
                'aplica_descuento_trago' => false,
                'stock' => 999,
                'precio_venta' => 10000,
                'descripcion' => 'Coca Cola 1 litro',
                'impuesto' => 0,
                'fecha_vencimiento' => null,
                'img_path' => null,
                'estado' => 1,
                'marca_id' => 1,
                'presentacione_id' => 4,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'codigo' => 'BEB002',
                'nombre' => 'Coca Cola 500 ml',
                'tipo_producto' => 'bebida',
                'aplica_descuento_trago' => false,
                'stock' => 999,
                'precio_venta' => 8000,
                'descripcion' => 'Coca Cola 500 ml',
                'impuesto' => 0,
                'fecha_vencimiento' => null,
                'img_path' => null,
                'estado' => 1,
                'marca_id' => 1,
                'presentacione_id' => 3,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'codigo' => 'BEB003',
                'nombre' => 'Coca Cola 250 ml',
                'tipo_producto' => 'bebida',
                'aplica_descuento_trago' => false,
                'stock' => 999,
                'precio_venta' => 4000,
                'descripcion' => 'Coca Cola 250 ml',
                'impuesto' => 0,
                'fecha_vencimiento' => null,
                'img_path' => null,
                'estado' => 1,
                'marca_id' => 1,
                'presentacione_id' => 2,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'codigo' => 'BEB004',
                'nombre' => 'Agua con gas 500 ml',
                'tipo_producto' => 'bebida',
                'aplica_descuento_trago' => false,
                'stock' => 999,
                'precio_venta' => 4000,
                'descripcion' => 'Agua con gas 500 ml',
                'impuesto' => 0,
                'fecha_vencimiento' => null,
                'img_path' => null,
                'estado' => 1,
                'marca_id' => 7,
                'presentacione_id' => 3,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'codigo' => 'BEB005',
                'nombre' => 'Agua sin gas 500 ml',
                'tipo_producto' => 'bebida',
                'aplica_descuento_trago' => false,
                'stock' => 999,
                'precio_venta' => 4000,
                'descripcion' => 'Agua sin gas 500 ml',
                'impuesto' => 0,
                'fecha_vencimiento' => null,
                'img_path' => null,
                'estado' => 1,
                'marca_id' => 7,
                'presentacione_id' => 3,
                'created_at' => now(),
                'updated_at' => now()
            ],

            // ========== CERVEZAS ==========
            [
                'codigo' => 'CER001',
                'nombre' => 'Münich Ultra 269 ml',
                'tipo_producto' => 'bebida',
                'aplica_descuento_trago' => false,
                'stock' => 999,
                'precio_venta' => 4000,
                'descripcion' => 'Cerveza Münich Ultra 269 ml',
                'impuesto' => 0,
                'fecha_vencimiento' => null,
                'img_path' => null,
                'estado' => 1,
                'marca_id' => 7,
                'presentacione_id' => 2,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'codigo' => 'CER002',
                'nombre' => 'Heineken Silver 269 ml',
                'tipo_producto' => 'bebida',
                'aplica_descuento_trago' => false,
                'stock' => 999,
                'precio_venta' => 7000,
                'descripcion' => 'Cerveza Heineken Silver 269 ml',
                'impuesto' => 0,
                'fecha_vencimiento' => null,
                'img_path' => null,
                'estado' => 1,
                'marca_id' => 7,
                'presentacione_id' => 2,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'codigo' => 'CER003',
                'nombre' => 'Pilsen 940 ml',
                'tipo_producto' => 'bebida',
                'aplica_descuento_trago' => false,
                'stock' => 999,
                'precio_venta' => 10000,
                'descripcion' => 'Cerveza Pilsen 940 ml',
                'impuesto' => 0,
                'fecha_vencimiento' => null,
                'img_path' => null,
                'estado' => 1,
                'marca_id' => 3,
                'presentacione_id' => 4,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'codigo' => 'CER004',
                'nombre' => 'Miller 600 ml',
                'tipo_producto' => 'bebida',
                'aplica_descuento_trago' => false,
                'stock' => 999,
                'precio_venta' => 12000,
                'descripcion' => 'Cerveza Miller 600 ml',
                'impuesto' => 0,
                'fecha_vencimiento' => null,
                'img_path' => null,
                'estado' => 1,
                'marca_id' => 7,
                'presentacione_id' => 3,
                'created_at' => now(),
                'updated_at' => now()
            ],
        ];

        // Insertar productos y asignar categorías
        foreach ($productos as $producto) {
            $productoId = DB::table('productos')->insertGetId($producto);
            
            // Asignar categoría según el código del producto
            $categoriaId = match(substr($producto['codigo'], 0, 3)) {
                'TRG', 'DAI', 'SAN', 'OTR' => 4, // Tragos Clásicos
                'SHT' => 5, // Shots
                'PAP' => 1, // Papas (Abarrotes)
                'PIZ' => 1, // Pizzas (Abarrotes)
                'HOT' => 1, // Hot Dogs (Abarrotes)
                'CMB' => 1, // Combos (Abarrotes)
                'BEB' => 2, // Bebidas Gaseosas
                'CER' => 3, // Cervezas
                default => 1
            };
            
            DB::table('categoria_producto')->insert([
                'categoria_id' => $categoriaId,
                'producto_id' => $productoId,
                'created_at' => now(),
                'updated_at' => now()
            ]);
        }

        echo "\n✅ Se han cargado " . count($productos) . " productos del menú del bar\n";
        echo "📋 Tragos: " . count(array_filter($productos, fn($p) => $p['tipo_producto'] === 'trago')) . "\n";
        echo "🍕 Comidas: " . count(array_filter($productos, fn($p) => $p['tipo_producto'] === 'comida')) . "\n";
        echo "🥤 Bebidas: " . count(array_filter($productos, fn($p) => $p['tipo_producto'] === 'bebida')) . "\n";
    }
}
